CREATE TABLE `advertisements`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `SURNAME` VARCHAR(45) NULL,
  `PHONE_NUMBER` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `REGISTRATION_DATE` DATE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC));